COLORS = {
    "blue":     "#4c78a8",
    "green":    "#9EA856",
    "red":      "#E0665C",
}


# guac ID and entrant's info
ENTRANTS = [
        {
        "ID":                   0,
        "Entrant":              "Clever Cleo",
        "One Clear Winner":     4,
        "A Close Call":         4,
        "A Lot of Contenders":  4,
        },
        {
        "ID":                   1,
        "Entrant":              "Lethargic Leslie",
        "One Clear Winner":     5,
        "A Close Call":         5,
        "A Lot of Contenders":  5,
        },
        {
        "ID":                   2,
        "Entrant":              "Delightful Doris",
        "One Clear Winner":     2,
        "A Close Call":         2,
        "A Lot of Contenders":  4,
        },
        {
        "ID":                   3,
        "Entrant":              "Persnickety Pierce",
        "One Clear Winner":     7,
        "A Close Call":         7,
        "A Lot of Contenders":  7,
        },
        {
        "ID":                   4,
        "Entrant":              "Allergenic Alyce",
        "One Clear Winner":     6,
        "A Close Call":         6,
        "A Lot of Contenders":  6,
        },
        {
        "ID":                   5,
        "Entrant":              "Yodelin' Yazmin",
        "One Clear Winner":     10,
        "A Close Call":         8,
        "A Lot of Contenders":  8,
        },
        {
        "ID":                   6,
        "Entrant":              "Hurried Hester",
        "One Clear Winner":     7,
        "A Close Call":         7,
        "A Lot of Contenders":  7,
        },
        {
        "ID":                   7,
        "Entrant":              "Mischevious Mischa",
        "One Clear Winner":     4,
        "A Close Call":         4,
        "A Lot of Contenders":  9,
        },
        {
        "ID":                   8,
        "Entrant":              "Cliquey Carlos",
        "One Clear Winner":     2,
        "A Close Call":         6,
        "A Lot of Contenders":  5,
        },
        {
        "ID":                   9,
        "Entrant":              "Jolly Julien",
        "One Clear Winner":     7,
        "A Close Call":         10,
        "A Lot of Contenders":  8,
        },
        {
        "ID":                   10,
        "Entrant":              "Carnivorous Chris",
        "One Clear Winner":     5,
        "A Close Call":         9.5,
        "A Lot of Contenders":  9.5,
        },
        {
        "ID":                   11,
        "Entrant":              "Muscular Mandy",
        "One Clear Winner":     2,
        "A Close Call":         2,
        "A Lot of Contenders":  8,
        },
        {
        "ID":                   12,
        "Entrant":              "Rare Rodrigo",
        "One Clear Winner":     5,
        "A Close Call":         5,
        "A Lot of Contenders":  10,
        },
        {
        "ID":                   13,
        "Entrant":              "Leprosy Lindsey",
        "One Clear Winner":     7,
        "A Close Call":         8,
        "A Lot of Contenders":  8,
        },
        {
        "ID":                   14,
        "Entrant":              "Marvelous Mia",
        "One Clear Winner":     2,
        "A Close Call":         3,
        "A Lot of Contenders":  9,
        },
        {
        "ID":                   15,
        "Entrant":              "Retired Ross",
        "One Clear Winner":     5,
        "A Close Call":         5,
        "A Lot of Contenders":  5,
        },
        {
        "ID":                   16,
        "Entrant":              "Zealous Zeashan",
        "One Clear Winner":     4,
        "A Close Call":         4,
        "A Lot of Contenders":  9,
        },
        {
        "ID":                   17,
        "Entrant":              "Workin' Wallace",
        "One Clear Winner":     7,
        "A Close Call":         7,
        "A Lot of Contenders":  7,
        },
        {
        "ID":                   18,
        "Entrant":              "Eccentric Esme",
        "One Clear Winner":     2,
        "A Close Call":         2,
        "A Lot of Contenders":  8,
        },
        {
        "ID":                   19,
        "Entrant":              "Corporate Connor",
        "One Clear Winner":     4,
        "A Close Call":         4,
        "A Lot of Contenders":  4,
        },
]


DEMO_CONTEST = [
    {
        "ID":                   0,
        "Entrant":              "Scrupulous Susie",
        "Objective Ratings":    9,
    },
    {
        "ID":                   1,
        "Entrant":              "Articulate Arnold",
        "Objective Ratings":    2,
    },
    {
        "ID":                   2,
        "Entrant":              "Gregarious Gregory",
        "Objective Ratings":    6,
    },
    # {
    #     "ID":                   3,
    #     "Entrant":              "Scrupulous Susie",
    #     "Objective Ratings":    4,
    # },
    # {
    #     "ID":                   4,
    #     "Entrant":              "Scrupulous Susie",
    #     "Objective Ratings":    4,
    # },
]


# OBJECTIVE_RATINGS = {
#     "One Clear Winner": [
#         4,
#         5,
#         2,
#         7,
#         6,
#         10,
#         7,
#         4,
#         2,
#         7,
#         5,
#         2,
#         5,
#         7,
#         2,
#         5,
#         4,
#         7,
#         2,
#         4,
#     ],

#     "A Close Call": [
#         4,
#         5,
#         2,
#         7,
#         6,
#         8,
#         7,
#         4,
#         6,
#         10,
#         9.5,
#         2,
#         5,
#         8,
#         3,
#         5,
#         4,
#         7,
#         2,
#         4,
#     ],

#     "A Lot of Contenders": [
#         4,
#         5,
#         4,
#         7,
#         6,
#         8,
#         7,
#         9,
#         8,
#         5,
#         9.5,
#         8,
#         10,
#         8,
#         9,
#         5,
#         9,
#         7,
#         8,
#         4,
#     ],
# }